name: "load-secrets"
description: "load env secrets into local.properties file"

runs:
  using: "composite"
  steps:
    - name: Load secrets
      shell: bash
      run: |
        echo "sdk.dir=$ANDROID_HOME" >> local.properties
        echo "DEBUG_APP_URL=\"${{ secrets.DEBUG_APP_URL }}\"" >> local.properties
        echo "PROD_APP_URL=\"${{ secrets.PROD_APP_URL }}\"" >> local.properties
        echo "FIREBASE_WEB_ID=\"${{ secrets.FIREBASE_WEB_ID }}\"" >> local.properties