name: Build debug app

on:
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest
    environment: App_Debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local.properties file
        uses: ./.github/actions/load_properties

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app
        run: ./gradlew :app:assembleDebug