name: Build debug app

on:
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest
    environment: App_Debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local.properties file
        uses: ./.github/actions/write-secrets
        with:
          firebase-web-id: ${{ secrets.FIREBASE_WEB_ID }}
          debug-api-url: ${{ secrets.DEBUG_APP_URL }}
          prod-api-url: ${{ secrets.PROD_APP_URL }}

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build app
        run: ./gradlew :app:assembleDebug