name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local.properties file
        run: |
          echo "sdk.dir=$ANDROID_HOME" >> local.properties
          echo "DEBUG_APP_URL=${{ secrets.DEBUG_APP_URL }}" >> local.properties
          echo "PROD_APP_URL=${{ secrets.PROD_APP_URL }}" >> local.properties
          echo "FIREBASE_WEB_ID=${{ secrets.FIREBASE_WEB_ID }}" >> local.properties

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test